### ISSUE TITLE
64 bit version of library?

### ISSUE THREAD

**Issue by scotzark** [ndahlquist/pngquant-android#17]
Hi-

Do you have a 64 bit version of the library built (arm64-v8a)?

Thanks,

Scot

**Comment by ndahlquist** [comment]
I have not done this. It looks like this fork has added that change though: https://github.com/wrmndfzzy/pngquant-android/commit/0839db2dba8d82e87bc30fd332b8dd1dbf210294

**Comment by scotzark** [comment]
Thanks!  Appreciate the feedback.
