### ISSUE TITLE
build error on mac

### ISSUE THREAD

**Issue by menshen** [ndahlquist/pngquant-android#7]
## **I get error when i build pngquant with command "./gradlew installDebug"**

the log is:

make: *** No rule to make target `jni/pngquant/rwpng.c', needed by `obj/local/arm64-v8a/objs/pngquant/pngquant/rwpng.o'.  Stop.
make: *** Waiting for unfinished jobs....
[arm64-v8a] Compile        : pngquantandroid <= native_glue.c
[arm64-v8a] Compile        : pngquantandroid <= pngquant.c
jni/native_glue.c:8:19: fatal error: rwpng.h: No such file or directory
 #include "rwpng.h"
                   ^
compilation terminated.
make: *** [obj/local/arm64-v8a/objs/pngquantandroid/native_glue.o] Error 1
In file included from jni/pngquant.c:50:0:
jni/pngquant.h:4:69: fatal error: rwpng.h: No such file or directory
 #include "rwpng.h"  /* typedefs, common macros, public prototypes */

**Comment by ndahlquist** [comment]
I believe this was caused by not initializing the submodules (see [building](https://github.com/ndahlquist/pngquant-android#building)):

`git submodule init; git submodule update`
