### ISSUE TITLE
No Result with run the nativePngQuantFile

### ISSUE THREAD

**Issue by CN-Tower** [ndahlquist/pngquant-android#9]
I encapsulated a cordova plugin base on your repo: https://github.com/CN-Tower/cordova-plugin-pngquant
But my outputfile is empty after run the nativePngQuantFile. Can you help me?
LogCat:
09-08 16:01:53.457 17558-17558/com.jcflash.android V/ActivityThread: >>> handling: ENABLE_JIT
09-08 16:01:53.457 17558-17558/com.jcflash.android V/ActivityThread: <<< done: ENABLE_JIT
09-08 16:02:05.945 17558-17558/com.jcflash.android D/SystemWebChromeClient: file:///android_asset/www/js/index.js: Line 36 : /9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABALDA4MChAODQ4SERATGCgaGBYW...
09-08 16:02:06.091 17558-17633/com.jcflash.android E/Input Filename: /storage/emulated/0/Android/data/com.jcflash.android/cache/temp1213492856png
09-08 16:02:06.092 17558-17633/com.jcflash.android E/Output Filename: /storage/emulated/0/Android/data/com.jcflash.android/cache/temp63894766png
09-08 16:02:06.092 17558-17633/com.jcflash.android I/LibPngQuantizer: /storage/emulated/0/Android/data/com.jcflash.android/cache/temp1213492856png:
09-08 16:02:06.093 17558-17633/com.jcflash.android E/Response Data: {"data":""}
09-08 16:02:06.093 17558-17633/com.jcflash.android W/PluginManager: THREAD WARNING: exec() call to PngQuant.compress blocked the main thread for 123ms. Plugin should use CordovaInterface.getThreadPool().
09-08 16:02:06.097 17558-17558/com.jcflash.android D/SystemWebChromeClient: file:///android_asset/www/js/index.js: Line 38 : [object Object]
09-08 16:02:06.097 17558-17558/com.jcflash.android I/chromium: [INFO:CONSOLE(38)] "[object Object]", source: file:///android_asset/www/js/index.js (38)

**Comment by ndahlquist** [comment]
Hi @CN-Tower , sorry I'm not familiar with Cordova. Are you able to test the Android implementation without Cordova? Or provide any more details?
